plugins:
  - rubocop-rspec

inherit_gem:
  rspec-sleeping_king_studios: config/rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - tmp/**/*
    - vendor/**/*

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  AllowedPatterns:
    - '\A\s*#'
  Max: 80

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - lib/**/*_contract.rb
    - lib/**/*_contracts.rb
    - lib/**/*_examples.rb
    - spec/support/**/*_examples.rb
    - spec/**/*_spec.rb

Metrics/ModuleLength:
  Exclude:
    - lib/**/*_contract.rb
    - lib/**/*_contracts.rb
    - lib/**/*_examples.rb
    - spec/**/*_examples.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/BeNil:
  Enabled: false

RSpec/Eq:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/IncludeExamples:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/integration/**/*

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ClassAndModuleChildren:
  Enabled: false

Style/NestedParenthesizedCalls:
  Exclude:
    - lib/**/*_contract.rb
    - 'spec/**/*'

Style/RedundantLineContinuation:
  Exclude:
    - 'spec/**/*'

Style/TrailingUnderscoreVariable:
  Enabled: false
