require:
  - rubocop-rspec
  - ./spec/support/rubocop_patch

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - vendor/**/*

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - lib/**/*_contract.rb
    - spec/support/**/*_examples.rb
    - spec/**/*_spec.rb

Metrics/ModuleLength:
  Exclude:
    - lib/**/*_contract.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ClassAndModuleChildren:
  Enabled: false

Style/NestedParenthesizedCalls:
  Exclude:
    - lib/**/*_contract.rb
    - 'spec/**/*'
