require:
  - rubocop-rspec

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - context
        - describe
        - wrap_context
      Skipped:
        - xcontext
        - xdescribe
        - xwrap_context
      Focused:
        - fcontext
        - fdescribe
        - fwrap_context
    Includes:
      Examples:
        - finclude_contract
        - finclude_examples
        - fwrap_examples
        - include_contract
        - include_examples
        - wrap_examples
        - xinclude_contract
        - xinclude_examples
        - xwrap_examples

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - tmp/**/*
    - vendor/**/*

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  AllowedPatterns:
    - '\A\s*#'
  Max: 80

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - lib/**/*_contract.rb
    - lib/**/*_contracts.rb
    - spec/support/**/*_examples.rb
    - spec/**/*_spec.rb

Metrics/ModuleLength:
  Exclude:
    - lib/**/*_contract.rb
    - lib/**/*_contracts.rb
    - spec/**/*_examples.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/BeNil:
  Enabled: false

RSpec/Eq:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/integration/**/*

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ClassAndModuleChildren:
  Enabled: false

Style/NestedParenthesizedCalls:
  Exclude:
    - lib/**/*_contract.rb
    - 'spec/**/*'

Style/TrailingUnderscoreVariable:
  Enabled: false
