require:
  - rubocop-rspec
  - ./spec/support/rubocop_patch

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - vendor/**/*

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle: table

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

RSpec/ExampleWording:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
